/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceeed",
        "secondary": "#3c6842",
        "on-primary-fixed-variant": "#005235",
        "surface-container-low": "#f2f4f3",
        "tertiary-fixed": "#ffddb5",
        "surface-container-high": "#e6e9e8",
        "secondary-fixed": "#bdefbe",
        "inverse-on-surface": "#eff1f0",
        "on-secondary-fixed": "#002109",
        "on-background": "#191c1c",
        "on-surface-variant": "#3e4942",
        "on-primary-fixed": "#002113",
        "surface-tint": "#006c47",
        "primary": "#006b47",
        "primary-fixed-dim": "#71dba6",
        "surface-dim": "#d8dad9",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#a2d3a4",
        "background": "#f8faf9",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#f8faf9",
        "on-error": "#ffffff",
        "on-primary-container": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1c",
        "surface-container-highest": "#e1e3e2",
        "tertiary-container": "#a36a00",
        "outline": "#6e7a71",
        "outline-variant": "#bdcac0",
        "on-error-container": "#93000a",
        "primary-container": "#00875a",
        "on-secondary-container": "#426e47",
        "tertiary-fixed-dim": "#ffb957",
        "tertiary": "#825400",
        "inverse-primary": "#71dba6",
        "on-tertiary-fixed-variant": "#643f00",
        "primary-fixed": "#8df7c1",
        "surface-variant": "#e1e3e2",
        "on-secondary-fixed-variant": "#24502c",
        "surface": "#f8faf9",
        "secondary-container": "#bdefbe",
        "inverse-surface": "#2e3131",
        "on-tertiary-container": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#2a1800",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
